apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/knative/operator/releases/download/knative-v1.12.1/operator.yaml
  - knative-serving.yaml
  - knative-eventing.yaml
